question_data = [
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
        "question": "This is the correct spelling of 'Supercalifragilisticexpialidocious';.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "There are 86400 seconds in a day.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The word news originates from the first letters of the 4 main directions on a compass (North, East, West, South).", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Bulls are attracted to the color red.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Ananas is mostly used as the word for Pineapple in other languages.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "The color orange is named after the fruit.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.", "correct_answer": "True", "incorrect_answers": [
        "False"]}, {"category": "General Knowledge", "type": "boolean", "difficulty": "medium", "question": "The French word to travel is Travail", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "One of Donald Trump'&'s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "Albert Einstein had trouble with mathematics when he was in school.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "27 Club is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The British organisation CAMRA stands for The Campaign for Real Ale.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "The commercial UK channel ITV stands for International Television.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "A pasodoble is a type of Italian pasta sauce.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Slovakia is a member of European Union-", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
        "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Jingle Bells was originally meant for Thanksgiving", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
        "question": "Ping-Pong originated in England", "correct_answer": "True", "incorrect_answers": ["False"]}
]
